name: Create Submodules
on:
    workflow_dispatch

jobs:
  create_submodules:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Iterate packages
         run: |
            packages='${{ vars.PACKAGES }}'
            for obj in $(echo "$packages" | jq -r '.[] | {name: .name, url: .url} | @base64'); do
              name=$(echo "$obj" | base64 --decode | jq -r '.name')
              url=$(echo "$obj" | base64 --decode | jq -r '.url')
              echo "Name: $name, Url: $url"
            done
